function Git_branch()
    local b = vim.fn.system("git branch --show-current")

    if b:find("fatal: not a git repository") then
        return nil
    else
        b = b:gsub("\n", "") -- trim newlines generated by the command
    end
    return b
end

vim.pack.add({
    {
        src = "https://github.com/kylechui/nvim-surround",
        version = "caf6f633d4d77a29b6e265b560c5a035d171a913",
    },
    {
        src = "https://github.com/nvim-tree/nvim-web-devicons",
        version = "4c3a5848ee0b09ecdea73adcd2a689190aeb728c",
    },
    {
        src = "https://github.com/nvim-lua/plenary.nvim",
        version = "3707cdb1e43f5cea73afb6037e6494e7ce847a66",
    },
})

Logger = require("logger").new({ print_log_entry = false })

require("options")
require("vim_keymaps")
require("autocommands")
require("harpun"):setup()
require("statusline")
require("file_exploring")
require("searching")
require("lsp")
require("sqlcmd")
require("completion")
require("nvim-surround").setup()
require("nvim-web-devicons").setup()

vim.diagnostic.config({
    virtual_text = true,
})

vim.o.bg = "light"
vim.cmd("colorscheme mycolorscheme")
