return {
    {
        --     'rebelot/kanagawa.nvim',
        --     lazy = false,
        --     commit = "cc3b68b08e6a0cb6e6bf9944932940091e49bb83",
        --     priority = 1000,
        --     enabled = false,
        --     compile = false, -- try setting this to true and run :KanagawaCompile and see if it gets faster
        --     config = function(config)
        --         local opts = {
        --             colors = {
        --                 theme = {
        --                     all = {
        --                         ui = {
        --                             bg_gutter = 'none',
        --                         },
        --                     },
        --                 },
        --             },
        --             undercurl = false,
        --             commentStyle = { italic = false },
        --             keywordStyle = { italic = false },
        --             statementStyle = { bold = false },
        --             background = {
        --                 dark = 'dragon',
        --                 light = "lotus"
        --
        --             },
        --             overrides = function(colors)
        --                 -- local p = colors.palette
        --                 -- local bg = p.lotusWhite3
        --                 -- local bg_darker = p.lotusWhite5
        --                 -- local text = p.sumiInk0
        --                 -- local comment = p.sumiInk6
        --                 -- local important = p.samuraiRed
        --                 -- local selection = p.lotusBlue3
        --                 --
        --                 -- local diff_add = p.lotusGreen -- or loturGreen2 // needs to be more vibrant
        --                 -- local diff_delete = p.samuraiRed
        --                 -- local diff_change = p.lotusOrange2
        --                 --
        --                 -- local diag_error = p.samuraiRed
        --                 -- local diag_warn = p.lotusOrange2
        --                 -- local diag_info = p.lotusBlue4 -- or lotusBlue5
        --                 -- local diag_hint = p.lotusInk1  -- same as comment
        --
        --                 local c = {
        --                     old_paper = "#f2ecbc",
        --                     light_grey = "#dcd7ba",
        --                     black = "#16161d",
        --                     red = "#e82424",
        --                     orange = "#e98a00",
        --                     blue = "#4dadd5",
        --                     dark_grey_blue = "#54546D", -- storm_blue?
        --                     green = "#5b9941",
        --                 }
        --                 local theme = {
        --                     bg = c.old_paper,
        --                     bg_2 = c.light_grey,
        --                     text = c.black,
        --                     comment = c.dark_grey_blue,
        --                     selection = c.blue,
        --                     important = c.red,
        --
        --                     error = c.red,
        --                     warning = c.orange,
        --                     info = c.blue,
        --                     hint = c.dark_grey_blue,
        --
        --                     diff_add = c.green,
        --                     diff_delete = c.red,
        --                     diff_change = c.orange
        --                 }
        --
        --                 local bg = theme.bg
        --                 local bg_darker = theme.bg_2
        --                 local text = theme.text
        --                 local comment = theme.comment
        --                 local important = theme.important
        --                 local selection = theme.selection
        --
        --                 local diff_add = theme.diff_add
        --                 local diff_delete = theme.diff_delete
        --                 local diff_change = theme.diff_change
        --
        --                 local diag_error = theme.error
        --                 local diag_warn = theme.warning
        --                 local diag_info = theme.info
        --                 local diag_hint = theme.hint
        --
        --                 -- lsp semantic tokens takes priority over treesitter.
        --                 -- This disables highlighting for given tokens
        --                 local function disable_lsp_semantic_token(tokens_by_lsp_client)
        --                     vim.api.nvim_create_autocmd("LspAttach", {
        --                         callback = function(args)
        --                             local client = vim.lsp.get_client_by_id(args.data.client_id)
        --                             local tokens = tokens_by_lsp_client[client.name]
        --                             if tokens then
        --                                 for _, token in pairs(tokens) do
        --                                     vim.api.nvim_set_hl(0, token, {})
        --                                 end
        --                             end
        --                         end
        --                     })
        --                 end
        --
        --                 disable_lsp_semantic_token({
        --                     lua_ls = {
        --                         "@lsp.type.property.lua",
        --                     },
        --                     rust_analyzer = {
        --                         "@lsp.type.keyword.rust",
        --                     }
        --                 })
        --
        --                 -- disable highlights for tokens.
        --                 local tokens = { "@keyword.vim" }
        --                 for _, token in pairs(tokens) do
        --                     vim.api.nvim_set_hl(0, token, {})
        --                 end
        --
        --                 return {
        --                     Normal         = { fg = text },
        --                     FloatBorder    = { fg = text, bg = "none" },
        --                     FloatTitle     = { fg = text, bg = "none" },
        --                     FloatFooter    = { fg = text, bg = "none" },
        --                     NormalFloat    = { bg = "none", fg = text },
        --                     CurSearch      = { bg = selection, bold = false },
        --                     CursorLineNr   = { fg = selection },
        --                     CursorLine     = { fg = text, bg = bg_darker },
        --                     CursorLineFold = { fg = text, bg = "none" },
        --                     CursorLineSign = { fg = text, bg = "none" },
        --                     IncSearch      = { fg = text, bg = selection },
        --                     Search         = { fg = text, bg = theme.bg_2 },
        --                     Substitute     = { fg = text, bg = theme.bg_2 },
        --                     LineNr         = { fg = text },
        --                     Visual         = { bg = theme.bg_2 },
        --                     MsgArea        = { fg = text, bg = "none" },
        --                     MsgSeparator   = { fg = text, bg = bg_darker },
        --
        --                     MoreMsg        = { fg = text, bg = "none" },
        --                     NoneText       = { fg = text, bg = "none" },
        --
        --                     Pmenu          = { fg = text, bg = bg_darker },
        --                     PmenuSel       = { fg = text, bg = bg_darker },
        --                     PmenuKind      = { fg = text, bg = bg_darker },
        --                     PmenuKindSel   = { fg = text, bg = bg_darker },
        --                     PmenuExtra     = { fg = text, bg = bg_darker },
        --                     PmenuExtraSel  = { fg = text, bg = bg_darker },
        --                     PmenuSbar      = { fg = text, bg = bg_darker },
        --                     PmenuThumb     = { fg = text, bg = bg_darker },
        --                     -- Maybe change these
        --                     -- PmenuMatch =
        --                     -- PmenuMatchSel =
        --
        --
        --                     DiffAdd                                             = { bg = diff_add },
        --                     DiffDelete                                          = { bg = diff_delete, fg = text, },
        --                     DiffChange                                          = { bg = diff_change },
        --                     ErrorMsg                                            = { fg = diag_error },
        --
        --                     DiagnosticError                                     = { fg = diag_error },
        --                     DiagnosticWarn                                      = { fg = diag_warn },
        --                     DiagnosticInfo                                      = { fg = diag_info },
        --                     DiagnosticHint                                      = { fg = diag_hint },
        --                     DiagnosticOk                                        = { fg = text },
        --
        --                     DiagnosticFloatingError                             = { fg = diag_error },
        --                     DiagnosticFloatingWarn                              = { fg = diag_warn },
        --                     DiagnosticFloatingInfo                              = { fg = diag_info },
        --                     DiagnosticFloatingHint                              = { fg = diag_hint },
        --                     DiagnosticFloatingOk                                = { fg = text },
        --
        --                     -- DiagnosticSignError        = { fg = diag_error, bg = theme.ui.bg_gutter },
        --                     DiagnosticSignError                                 = { fg = diag_error, bg = bg },
        --                     DiagnosticSignWarn                                  = { fg = diag_warn, bg = bg },
        --                     DiagnosticSignInfo                                  = { fg = diag_info, bg = bg },
        --                     DiagnosticSignHint                                  = { fg = diag_hint, bg = bg },
        --
        --                     DiagnosticVirtualTextError                          = { link = "DiagnosticError" },
        --                     DiagnosticVirtualTextWarn                           = { link = "DiagnosticWarn" },
        --                     DiagnosticVirtualTextInfo                           = { link = "DiagnosticInfo" },
        --                     DiagnosticVirtualTextHint                           = { link = "DiagnosticHint" },
        --
        --                     DiagnosticUnderlineError                            = { undercurl = config.undercurl, underline = not config.undercurl, sp = diag_error },
        --                     DiagnosticUnderlineWarn                             = { undercurl = config.undercurl, underline = not config.undercurl, sp = diag_warn },
        --                     DiagnosticUnderlineInfo                             = { undercurl = config.undercurl, underline = not config.undercurl, sp = diag_info },
        --                     DiagnosticUnderlineHint                             = { undercurl = config.undercurl, underline = not config.undercurl, sp = diag_hint },
        --
        --                     diffAdded                                           = { fg = diff_add },
        --                     diffRemoved                                         = { fg = diff_delete },
        --                     diffDeleted                                         = { fg = diff_delete },
        --                     diffChanged                                         = { fg = diff_change },
        --                     diffOldFile                                         = { fg = diff_delete },
        --                     diffNewFile                                         = { fg = diff_add },
        --
        --                     -- blink (completion)
        --                     BlinkCmpMenu                                        = { bg = bg, },
        --                     BlinkCmpMenuBorder                                  = { bg = "none", },
        --                     BlinkCmpMenuSelection                               = { bg = bg_darker },
        --                     BlinkCmpLabel                                       = { bg = bg, fg = text },
        --                     BlinkCmpDoc                                         = { bg = "none", },
        --                     BlinkCmpDocBorder                                   = { bg = "none", },
        --                     BlinkCmpLabelMatch                                  = { fg = theme.selection },
        --
        --                     -- fzf
        --                     FzfLuaBufLineNr                                     = { fg = text, bg = "none" },
        --                     FzfLuaFzfNormal                                     = { fg = text, bg = "none" },
        --                     FzfLuaNormal                                        = { fg = text, bg = "none" },
        --                     FzfLuaSearch                                        = { link = "CurSearch" },
        --                     FzfLuaBufName                                       = { fg = text },
        --                     FzfLuaLivePrompt                                    = { fg = text, bg = "none" },
        --                     FzfLuaDirPart                                       = { fg = text, bg = "none" },
        --                     FzfLuaFilePart                                      = { fg = text, bg = "none" },
        --                     FzfLuaFzfMatch                                      = { fg = selection },
        --                     FzfLuaFzfPrompt                                     = { fg = text, bg = "none" },
        --                     FzfLuaFzfPointer                                    = { fg = text, bg = "none" },
        --                     FzfLuaFzfInfo                                       = { fg = text, bg = "none" },
        --                     FzfLuaLiveSym                                       = { fg = text, bg = "none" },
        --                     FzfLuaTabTitle                                      = { fg = text, bg = "none" },
        --                     FzfLuaBufNr                                         = { fg = text, bg = "none" },
        --                     FzfLuaCursorLineNr                                  = { fg = text, bg = "none" },
        --                     FzfLuaTitleFlags                                    = { fg = text, bg = "none" },
        --
        --                     -- syntax
        --                     Boolean                                             = { fg = text, bold = false },
        --                     Number                                              = { fg = text },
        --                     Constant                                            = { fg = text },
        --                     Identifier                                          = { fg = text },
        --                     Function                                            = { fg = text, bold = false },
        --                     Statement                                           = { fg = text },
        --                     Operator                                            = { fg = text },
        --                     Keyword                                             = { fg = text },
        --                     Exception                                           = { fg = important },
        --                     PreProc                                             = { fg = text },
        --                     Type                                                = { fg = text, bold = false },
        --                     Special                                             = { fg = text },
        --                     Delimiter                                           = { fg = text },
        --                     Underlined                                          = { fg = text },
        --                     Bold                                                = { bold = false },
        --                     Italic                                              = { italic = false },
        --                     Comment                                             = { fg = comment },
        --                     String                                              = { fg = text },
        --
        --                     -- syntax yaml
        --                     yamlPlainScalar                                     = { fg = text },
        --
        --                     -- syntax docker
        --                     dockerfileShell                                     = { fg = text },
        --                     dockerfileValue                                     = { fg = text },
        --                     dockerfileInstruction                               = { fg = text },
        --                     dockerfileFrom                                      = { fg = text },
        --
        --                     -- treesitter
        --                     ["@variable"]                                       = { fg = text },
        --                     ["@variable.builtin"]                               = { fg = text, italic = false },
        --                     ["@variable.parameter"]                             = { fg = text },
        --                     ["@variable.member"]                                = { fg = text },
        --                     ["@string.special.symbol"]                          = { fg = text },
        --                     ["@attribute"]                                      = { fg = text },
        --                     ["@constructor"]                                    = { fg = text },
        --                     ["@operator"]                                       = { fg = text },
        --                     ["@keyword.operator"]                               = { fg = text, bold = false },
        --                     ["@keyword.return"]                                 = { fg = important },
        --                     ["@keyword.import"]                                 = { fg = text },
        --                     ["@keyword.exception"]                              = { fg = important },
        --                     ["@punctuation.delimiter"]                          = { fg = text },
        --                     ["@punctuation.bracket"]                            = { fg = text },
        --                     ["@punctuation.special"]                            = { fg = text },
        --
        --                     -- c#
        --                     ["@keyword.operator.c_sharp"]                       = { fg = text },
        --                     ["@variable.builtin.c_sharp"]                       = { fg = text },
        --                     ["@keyword.return.c_sharp"]                         = { fg = important },
        --                     ["@attribute.c_sharp"]                              = { fg = text },
        --
        --                     -- lua
        --                     ["@keyword.operator.lua"]                           = { fg = text },
        --                     ["@keyword.return.lua"]                             = { fg = important },
        --                     ["@keyword.import.c_sharp"]                         = { fg = text },
        --                     ["@constructor.lua"]                                = { fg = text },
        --                     ["@string.regexp.lua"]                              = { fg = text },
        --                     ["@string.escape.lua"]                              = { fg = text },
        --
        --                     -- rust
        --                     ["@keyword.return.rust"]                            = { fg = important },
        --                     ["@keyword.import.rust"]                            = { fg = text },
        --                     ["@lsp.type.enumMember.rust"]                       = { fg = text },
        --                     ["@lsp.type.macro.rust"]                            = { fg = text },
        --                     ["@lsp.typemod.method.defaultLibrary.rust"]         = { fg = text },
        --                     ["@lsp.typemod.function.defaultLibrary.rust"]       = { fg = text },
        --                     ["@character.special.rust"]                         = { fg = text },
        --                     ["@lsp.type.decorator.rust"]                        = { fg = text },
        --                     ["@function.call.rust"]                             = { fg = text },
        --
        --                     -- vue
        --                     ["@lsp.typemod.function.readonly.vue"]              = { fg = text },
        --                     ["@lsp.typemod.variable.defaultLibrary.vue"]        = { fg = text },
        --
        --                     -- typescript
        --                     ["@lsp.typemod.function.readonly.typescript"]       = { fg = text },
        --                     ["@lsp.typemod.function.readonly.javascript"]       = { fg = text },
        --                     ["@lsp.typemod.variable.defaultLibrary.typescript"] = { fg = text },
        --                     ["@keyword.return.typescript"]                      = { fg = important },
        --
        --                     -- vim
        --                     ["@function.macro.vim"]                             = { fg = text },
        --                 }
        --             end,
        --         }
        --         require('kanagawa').setup(opts)
        --         vim.opt.background = 'light'
        --         vim.cmd('colorscheme kanagawa')
        --     end
    },
}
